### ISSUE TITLE
missing WIF CHARACTERS

### ISSUE THREAD

**Issue by Handsomekaizer** [10gic/ethutil#6]
Hello sir
Sorry to bother I was just going through your repo to see if you could help me. The problem I have is with my wallet private key characters, I mistakenly damaged the piece of paper I wrote it on, so I was wondering if you could help me write a program that will brute Force all the 10 missing characters very fast and find the correct characters and in return I will make a donation of 2 BTC to you if I find the correct keys

**Comment by 10gic** [comment]
@Handsomekaizer How can I contact you directly, can you tell me your email? There are some details I want to confirm with you.

**Comment by Handsomekaizer** [comment]
Here is my email
***@***.***

**Comment by 10gic** [comment]
Only show:
<img width="138" alt="image" src="https://user-images.githubusercontent.com/2391796/173047793-9758a5ba-0c8e-49bc-9e0e-451c860e1b76.png">

Can't see your email, maybe it's hidden by github.

**Comment by Handsomekaizer** [comment]
ubongetimanthony@gmail.com

**Comment by 10gic** [comment]
Okay, I know. I removed you reply for privacy.
